"""increase user manage

Revision ID: 008cec83c552
Revises: d13e4804443e
Create Date: 2017-09-08 18:56:19.228638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '008cec83c552'
down_revision = 'd13e4804443e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('default', sa.Boolean(), nullable=True))
    op.add_column('roles', sa.Column('permissions', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.drop_column('roles', 'permissions')
    op.drop_column('roles', 'default')
    # ### end Alembic commands ###
