"""add is_confirmed attibute

Revision ID: d13e4804443e
Revises: 8824e5ad7a2d
Create Date: 2017-09-08 10:34:03.689712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd13e4804443e'
down_revision = '8824e5ad7a2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_confirmed')
    # ### end Alembic commands ###
